### ISSUE TITLE
[Feature] Keeping StackExchange styles, printing singular posts.

### ISSUE THREAD

**Issue by ajarzyn** [systempuntoout/stackprinter#3]
Hello,

Nice solution thank you for that. Do you have any plans to extend application?

I would like to suggest three things:
1. Option to keep formating of the StackExchange. You know all this fancy buttons, and decoratives that Stack does.
2. Possibility to print only particular post. (You can share posts using share button, which could be used to fetch only this post information ie. https://superuser.com/a/362115/1291940 )
3. Parsing shared link. As in point 2, it would be nice to post only url shared by Stack.

Thank you for your work.
Keep going!

**Comment by systempuntoout** [comment]
Hi there
thank you for your nice feedback.

You can actually print a specific answer:
http://www.stackprinter.com/export?question=362113&service=superuser&answer=362115
Please have a look to the simple API doc:
http://www.stackprinter.com/docs/api.txt

Michele

**Comment by ajarzyn** [comment]
That's grate thank you for pointing that out but I feel like I didn't know that because of faulty design it wasn't obvious that you can actually do that.

As the user who stumbled upon your app I did not expected that you can play with parameters I simply checked main option and did not dig deeper.

Of course it's not a big deal and what I've written is merely a suggestion, and I do not expect from you to change it for me.

I think that my third proposition to parse link could solve this problem without need for implementing additional flows for frontend.

Anyway the one I really hoped for is first proposition regarding formatting but it feels like lot's of work to do.

Thanks again for your time,
Andrzej
